name: DamiXKoTH
version: '1.0'
main: ar.com.octaviofarias.koth.DamiXKoTH
api-version: '1.21'
authors: [ DamianFarias ]
softdepend:
  - PlaceholderAPI
description: An easy and feature King of The Hill Minecraft Plugin
website: https://octaviofarias.com.ar
commands:
  koth:
    aliases:
      - koths
      - kingofthehill
      - damixkoth
      - damixkoths
    description: "Main DamiXKoth's Command"