menus:
  rewards:
    title: "&0%name%'s koth items rewards&r"
    rows: 6
# This placeholder is used when need to represent nobody in a placeholder like %damixkoth_dominating_name_kothname%
# If it returns null then we replace it for that placeholder
nobody-placeholder: "&cNobody"

yes-placeholder: "&aYes"
no-placeholder: "&cNo"

unavailable-placeholder: "&cUnavailable"

location-format: "&a%x%&f, &a%y%&f, &a%z%&f, &e%world%" # Example: &a10&f, &a71&f, &a43&f, &esurvivalworld

# This format is used when we have to represent seconds to a formal format like "mm:ss"
# Example how this look: 40:12
# 40 minute and 12 seconds
# To add hour time you have to put "hh:" before "mm"
time-format: "mm:ss"

# We use the time zone to check koths schedulers, for that it's obligatory insert one
# Check that the time zone is in your region in this page: https://www.timeanddate.com/time/map/
time-zone: "UTC-3"

# Don't touch this!
config-version: 1